{
    "openapi": "3.0.0",
    "info": {
        "title": "倍而兔募資平台",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://{{url}}"
        }
    ],
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    },
    "security": [
        {
            "bearerAuth": []
        }
    ],
    "paths": {
        "/signup": {
            "post": {
                "tags": [
                    "default"
                ],
                "summary": "S1-註冊",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "email": "c1_12345678@test.com",
                                    "pass": "12345678",
                                    "name": "a2",
                                    "method": 0,
                                    "oauth_google_id": "123"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/signin": {
            "post": {
                "tags": [
                    "default"
                ],
                "summary": "S2-登入",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "method": 0,
                                    "email": "c1_12345678@test.com",
                                    "pass": "12345678",
                                    "oauth_google_id": "123",
                                    "forget": false
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/me/user": {
            "put": {
                "tags": [
                    "default"
                ],
                "summary": "C3-更新我的會員資料",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "AAnne",
                                    "cover": "https://showanne.github.io/src/img/avatar_Anne.jpg",
                                    "phone": "988123123",
                                    "intro": "hello Anne",
                                    "website": "https://showanne.github.io/",
                                    "interests": [
                                        "read"
                                    ]
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "default"
                ],
                "summary": "C4-取得我的會員資料",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/owner/projects": {
            "post": {
                "tags": [
                    "default"
                ],
                "summary": "B1-新增專案內容",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "title": "標題",
                                    "summary": "project summary",
                                    "content": "project content",
                                    "category": "校園",
                                    "target": 12000,
                                    "progress": 0,
                                    "status": 0,
                                    "update_date": "2023-01-23",
                                    "update_final_member": "member",
                                    "cover": "cover URL",
                                    "video": "project video URL",
                                    "risks": "the risks",
                                    "owner": "6453d211c6ab8c4bfc26717d",
                                    "option": [
                                        "6453d211c6ab8c4bfc26717d"
                                    ]
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "default"
                ],
                "summary": "B2-列出專案",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/owner/projects/{projectId}": {
            "get": {
                "tags": [
                    "default"
                ],
                "summary": "B3-取得專案詳細內容",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "projectId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "default"
                ],
                "summary": "B4-修改專案內容",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "title": "修改標題",
                                    "status": 2
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "projectId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "default"
                ],
                "summary": "B5-刪除專案",
                "parameters": [
                    {
                        "name": "projectId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/owner/projects/{projectId}/options": {
            "post": {
                "tags": [
                    "default"
                ],
                "summary": "B6-新增方案內容",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "方案名稱2",
                                    "price": 1000,
                                    "total": 50,
                                    "content": "說明",
                                    "cover": "cover URL",
                                    "start_date": "2023-01-23",
                                    "end_date": "2023-04-23"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "projectId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "default"
                ],
                "summary": "B7-列出專案之方案內容",
                "parameters": [
                    {
                        "name": "projectId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/owner/projects/{projectId}/options/6460c4fe5c37bd19a64b9955": {
            "patch": {
                "tags": [
                    "default"
                ],
                "summary": "B9-修改某方案內容",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "方案名稱2-2",
                                    "status": 2
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "projectId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "tags": [
                    "default"
                ],
                "summary": "S7-搜尋專案",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "type",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        },
                        "example": "校園"
                    },
                    {
                        "name": "k",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        },
                        "example": "標題"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/projects/{projectId}": {
            "get": {
                "tags": [
                    "default"
                ],
                "summary": "S5-取得專案內容",
                "parameters": [
                    {
                        "name": "projectId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/projects/{projectId}/options": {
            "get": {
                "tags": [
                    "default"
                ],
                "summary": "S6-列出專案之方案內容",
                "parameters": [
                    {
                        "name": "projectId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/me/likes": {
            "post": {
                "tags": [
                    "default"
                ],
                "summary": "C7-收藏專案",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "pid": "6459fab141b8f20460c5856d"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "default"
                ],
                "summary": "C12-取得我的收藏專案",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/me/likes/{pid}": {
            "delete": {
                "tags": [
                    "default"
                ],
                "summary": "C11-刪除收藏專案",
                "parameters": [
                    {
                        "name": "pid",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/orders": {
            "post": {
                "tags": [
                    "default"
                ],
                "summary": "C1-贊助專案",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "user_id": "6460c3a55c37bd19a64b993d",
                                    "project_id": "6460c4185c37bd19a64b9943",
                                    "option_id": "6460c4fe5c37bd19a64b9955",
                                    "order_option_quantity": 1,
                                    "order_extra": 0,
                                    "order_total": 1000,
                                    "order_note": "testing orders",
                                    "payment_method": "信用卡",
                                    "invoice_type": "紙本發票",
                                    "invoice_carrier": ""
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/me/orders": {
            "get": {
                "tags": [
                    "default"
                ],
                "summary": "C2-分頁列出會員的贊助專案",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "page",
                        "in": "query",
                        "schema": {
                            "type": "integer"
                        },
                        "example": "1"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        }
    }
}